baseurl = "http://sunwxg.github.io/"
languageCode = "en-us"
title = "Sun Wang's Blog"
theme = "my_theme"

pygmentsStyle = "default"
PygmentsCodeFences = "true"

[Params]
  author = "Sun Wang"
  toc = true
